import * as T from'three';import{OrbitControls as O}from'three/addons/controls/OrbitControls.js';import{GLTFLoader as L}from'three/addons/loaders/GLTFLoader.js';import{GLTFExporter as E}from'three/addons/exporters/GLTFExporter.js';
const $=x=>document.getElementById(x),v=$('viewport'),s=new T.Scene(),c=new T.PerspectiveCamera(45,1,.01,1e4),r=new T.WebGLRenderer({antialias:1,preserveDrawingBuffer:1}),o=new O(c,r.domElement),A={root:null,parts:[],pal:[],n:0,name:'model.glb',up:null,w:[]};s.background=new T.Color(0x111820);c.position.set(3,2,4);r.setPixelRatio(Math.min(devicePixelRatio||1,2));r.outputColorSpace=T.SRGBColorSpace;r.toneMapping=T.ACESFilmicToneMapping;v.appendChild(r.domElement);o.enableDamping=1;s.add(new T.HemisphereLight(0xffffff,0x334455,2.2));let dl=new T.DirectionalLight(0xffffff,2.6);dl.position.set(4,8,6);s.add(dl);let grid=new T.GridHelper(20,40,0x536272,0x2b3540);s.add(grid);
const msg=x=>{$('status').textContent=x;$('statusPill').textContent=x},lab=q=>{let[a,b,d]=q,x=(a*.4124+b*.3576+d*.1805)/.95047,y=a*.2126+b*.7152+d*.0722,z=(a*.0193+b*.1192+d*.9505)/1.08883,f=t=>t>.008856?Math.cbrt(t):7.787*t+16/116;x=f(x);y=f(y);z=f(z);return[116*y-16,500*(x-y),200*(y-z)]},D=(a,b)=>{a=lab(a);b=lab(b);return Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2])},mean=(fs,p)=>{let q=[0,0,0];for(let f of fs){let x=p.fc[f];q[0]+=x[0];q[1]+=x[1];q[2]+=x[2]}return q.map(x=>x/Math.max(1,fs.length))};
function rs(){let b=v.getBoundingClientRect();if(!b.width)return;c.aspect=b.width/b.height;c.updateProjectionMatrix();r.setSize(b.width,b.height,!1)}new ResizeObserver(rs).observe(v);(function z(){requestAnimationFrame(z);o.update();r.render(s,c)})();
function stats(){let n=A.parts.reduce((x,p)=>x+p.n,0);$('trianglesStat').textContent=n.toLocaleString();$('groupsStat').textContent=A.n.toLocaleString();$('meshesStat').textContent=A.parts.length;$('paletteStat').textContent=A.pal.length;for(let id of['frameBtn','generateBtn','exportBtn','showOriginalBtn'])$(id).disabled=!A.root;$('randomiseBtn').disabled=!A.n}
function clear(){if(A.root)s.remove(A.root);A.root=null;A.parts=[];A.pal=[];A.n=0;$('meshName').textContent='No mesh loaded';lists();stats()}
function frame(){if(!A.root)return;let b=new T.Box3().setFromObject(A.root),z=b.getSize(new T.Vector3()),m=b.getCenter(new T.Vector3()),d=Math.max(z.x,z.y,z.z)||1;o.target.copy(m);c.position.copy(m).add(new T.Vector3(d*1.5,d*.9,d*1.5));c.near=Math.max(d/1e3,.001);c.far=d*1e3;c.updateProjectionMatrix()}
function adj(p){let n=p.count/3,M=new Map(),a=Array.from({length:n},()=>new Set),k=i=>`${Math.round(p.getX(i)*1e5)},${Math.round(p.getY(i)*1e5)},${Math.round(p.getZ(i)*1e5)}`;for(let f=0;f<n;f++){let v=[k(f*3),k(f*3+1),k(f*3+2)];for(let[i,j]of[[0,1],[1,2],[2,0]]){let e=v[i]<v[j]?v[i]+'|'+v[j]:v[j]+'|'+v[i];(M.get(e)||M.set(e,[]).get(e)).push(f)}}for(let x of M.values())for(let i=0;i<x.length;i++)for(let j=i+1;j<x.length;j++)a[x[i]].add(x[j]),a[x[j]].add(x[i]);return a}
const lin=x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4;
function tex(im){let C=document.createElement('canvas'),x=C.getContext('2d',{willReadFrequently:1});C.width=im.width;C.height=im.height;x.drawImage(im,0,0);return{w:C.width,h:C.height,d:x.getImageData(0,0,C.width,C.height).data}}
function sample(t,u,v){u=((u%1)+1)%1;v=((v%1)+1)%1;let x=Math.round(u*(t.w-1)),y=Math.round((1-v)*(t.h-1)),i=(y*t.w+x)*4;return[lin(t.d[i]/255),lin(t.d[i+1]/255),lin(t.d[i+2]/255)]}
async function prep(m){let g=m.geometry.index?m.geometry.toNonIndexed():m.geometry.clone();g.computeVertexNormals();m.geometry=g;let ms=Array.isArray(m.material)?m.material:[m.material],mp=ms.find(x=>x?.map)?.map,tx=mp?.image?tex(mp.image):null;return{m,orig:m.material,p:g.attributes.position,no:g.attributes.normal,uv:g.attributes.uv,col:g.attributes.color,n:g.attributes.position.count/3,a:adj(g.attributes.position),tx,fc:[],ids:null,groups:[],am:[],rm:[]}}
function face(p,f){let uv=p.uv,tx=A.up||p.tx;if(tx&&uv){let u=0,v=0;for(let k=0;k<3;k++)u+=uv.getX(f*3+k)/3,v+=uv.getY(f*3+k)/3;return sample(tx,u,v)}let m=Array.isArray(p.orig)?p.orig[0]:p.orig,x=m?.color||new T.Color(1,1,1);return[x.r,x.g,x.b]}
function nearest(x,p){let k=0,d=1e9;for(let i=0;i<p.length;i++){let q=D(x,p[i]);if(q<d)d=q,k=i}return k}
function palette(k,it){let all=A.parts.flatMap(p=>p.fc),step=Math.max(1,Math.floor(all.length/6000)),q=all.filter((_,i)=>i%step===0),p=[];for(let i=0;i<k;i++)p.push(q[Math.floor((i+.5)*q.length/k)]?.slice()||[.5,.5,.5]);for(let n=0;n<it;n++){let b=Array.from({length:k},()=>[]);for(let x of q)b[nearest(x,p)].push(x);for(let i=0;i<k;i++)if(b[i].length){let z=[0,0,0];for(let x of b[i])z=z.map((v,j)=>v+x[j]);p[i]=z.map(v=>v/b[i].length)}}return p}
function islands(p){let seen=new Uint8Array(p.n),R=[];for(let seed=0;seed<p.n;seed++){if(seen[seed])continue;let id=p.ids[seed],q=[seed],fs=[];seen[seed]=1;while(q.length){let f=q.pop();fs.push(f);p.a[f].forEach(n=>{if(!seen[n]&&p.ids[n]===id)seen[n]=1,q.push(n)})}R.push({id:R.length,pid:id,fs,alive:1})}return R}
function smooth(p,n,t){for(let z=0;z<n;z++){let nx=new Int32Array(p.ids),ch=0;for(let f=0;f<p.n;f++){let ns=[...p.a[f]],M=new Map;for(let x of ns)M.set(p.ids[x],(M.get(p.ids[x])||0)+1);let b=p.ids[f],m=0;M.forEach((v,k)=>{if(v>m)m=v,b=k});if(b!==p.ids[f]&&m/ns.length>=t)nx[f]=b,ch++}p.ids=nx;if(!ch)break}}
function clean(p,min,passes){for(let z=0;z<passes;z++){let ch=0;for(let r of islands(p)){if(r.fs.length>=min)continue;let M=new Map;r.fs.forEach(f=>p.a[f].forEach(n=>{let id=p.ids[n];if(id!==r.pid)M.set(id,(M.get(id)||0)+1)}));let b=r.pid,m=0;M.forEach((v,k)=>{if(v>m)m=v,b=k});if(b!==r.pid)r.fs.forEach(f=>p.ids[f]=b),ch++}if(!ch)break}}
function graph(p){let R=islands(p),fr=new Int32Array(p.n);R.forEach((r,i)=>r.fs.forEach(f=>fr[f]=i));R.forEach(r=>r.ne=new Set);for(let f=0;f<p.n;f++)p.a[f].forEach(n=>{let a=fr[f],b=fr[n];if(a!==b)R[a].ne.add(b),R[b].ne.add(a)});return[R,fr]}
function contrast(a,b,p,fr){let q=0,n=0;for(let f of a.fs)p.a[f].forEach(x=>{if(fr[x]===b.id)q+=D(p.fc[f],p.fc[x]),n++});return n?q/n:1e9}
function compact(a,p,fr){let q=0,n=0;for(let f of a.fs)p.a[f].forEach(x=>{n++;if(fr[x]!==a.id)q++});return n?1-q/n:0}
function reduce(R,p,fr,S){for(let z=0;z<S.pass;z++){let ch=0;for(let a of R.filter(x=>x.alive).sort((x,y)=>x.fs.length-y.fs.length)){if(!a.alive||a.fs.length>=S.below)continue;let mc=0;a.ne.forEach(i=>{let b=R[i];if(b?.alive)mc=Math.max(mc,contrast(a,b,p,fr))});if(S.protect&&a.fs.length<=S.ps&&mc>=S.ct&&compact(a,p,fr)>.45)continue;let best=null,score=-1e9;for(let i of a.ne){let b=R[i];if(!b?.alive)continue;let cd=D(mean(a.fs,p),mean(b.fs,p)),bc=contrast(a,b,p,fr);if(cd>S.max||S.protect&&bc>=S.ct)continue;let sb=0;for(let f of a.fs)p.a[f].forEach(x=>{if(fr[x]===b.id)sb++});let sc=sb*4+compact(b,p,fr)*S.cb-cd*.8-bc*.6+Math.log1p(b.fs.length);if(sc>score)score=sc,best=b}if(!best)continue;a.fs.forEach(f=>{best.fs.push(f);fr[f]=best.id});a.ne.forEach(i=>{let n=R[i];if(n?.alive&&n!==best)n.ne.delete(a.id),n.ne.add(best.id),best.ne.add(n.id)});best.ne.delete(a.id);best.ne.delete(best.id);a.alive=0;ch++}if(!ch)break}return R.filter(x=>x.alive)}
function mat(x){return new T.MeshStandardMaterial({color:new T.Color(...x),roughness:.72,side:T.DoubleSide})}
function rebuild(p,G){let P=[],N=[],U=[],g=new T.BufferGeometry,start=0;p.am.forEach(x=>x.dispose());p.rm.forEach(x=>x.dispose());p.am=[];p.rm=[];for(let i=0;i<G.length;i++){let x=G[i];for(let f of x.fs)for(let k=0;k<3;k++){let j=f*3+k;P.push(p.p.getX(j),p.p.getY(j),p.p.getZ(j));N.push(p.no.getX(j),p.no.getY(j),p.no.getZ(j));if(p.uv)U.push(p.uv.getX(j),p.uv.getY(j))}g.addGroup(start,x.fs.length*3,i);start+=x.fs.length*3;p.am.push(mat(x.mean));p.rm.push(mat(new T.Color().setHSL(Math.random(),.65,.55).toArray()))}g.setAttribute('position',new T.Float32BufferAttribute(P,3));g.setAttribute('normal',new T.Float32BufferAttribute(N,3));if(U.length)g.setAttribute('uv',new T.Float32BufferAttribute(U,2));p.m.geometry=g}
function gen(){try{msg('Sampling albedo…');A.parts.forEach(p=>p.fc=Array.from({length:p.n},(_,f)=>face(p,f)));A.pal=palette(+$('paletteSize').value,+$('paletteIterations').value);let total=0;for(let p of A.parts){p.ids=Int32Array.from(p.fc.map(x=>nearest(x,A.pal)));smooth(p,+$('neighbourPasses').value,+$('majorityThreshold').value);if($('mergeTiny').checked)clean(p,+$('minGroupSize').value,+$('cleanupPasses').value);let[R,fr]=graph(p);if($('mergeRegions').checked)R=reduce(R,p,fr,{below:+$('mergeBelow').value,pass:+$('regionMergePasses').value,max:+$('maxRegionColourDistance').value,protect:$('protectFeatureRegions').checked,ct:+$('boundaryContrastThreshold').value,ps:+$('protectedRegionSize').value,cb:+$('compactnessBias').value});let G=$('disconnectedMode').value==='global'?[...new Set(R.map(x=>x.pid))].map(pid=>{let fs=R.filter(x=>x.pid===pid).flatMap(x=>x.fs);return{pid,fs,mean:mean(fs,p)}}):R.map(x=>({pid:x.pid,fs:x.fs,mean:mean(x.fs,p)}));p.groups=G.map((x,i)=>({id:total+i+1,...x}));rebuild(p,p.groups);total+=G.length}A.n=total;lists();$('previewMode').value='groupAverage';preview();stats();msg(`Generated ${total} protected region facegroups.`)}catch(e){console.error(e);msg('Generation failed: '+e.message)}}
function preview(){A.parts.forEach(p=>p.m.material=$('previewMode').value==='original'?p.orig:$('previewMode').value==='random'?p.rm:p.am)}
function lists(){let pl=$('paletteList'),gl=$('groupList');pl.innerHTML='';gl.innerHTML='';A.pal.forEach((x,i)=>{let d=document.createElement('div'),h=new T.Color(...x).getHexString();d.className='groupRow';d.innerHTML=`<div class="swatch" style="background:#${h}"></div><div>Palette ${i+1}</div><small>P${i+1}</small>`;pl.appendChild(d)});let G=A.parts.flatMap(p=>p.groups||[]);if(!G.length)return gl.innerHTML='<div class="empty">Generate facegroups to inspect colour regions.</div>';G.forEach(x=>{let d=document.createElement('div'),h=new T.Color(...x.mean).getHexString();d.className='groupRow';d.innerHTML=`<div class="swatch" style="background:#${h}"></div><div><div>Group ${x.id}</div><small>${x.fs.length.toLocaleString()} faces · P${x.pid+1}</small></div><small>#${x.id}</small>`;gl.appendChild(d)})}
async function load(f){if(!f)return;clear();A.name=f.name;msg('Loading GLB…');let buf=await f.arrayBuffer(),g=await new Promise((a,b)=>new L().parse(buf,'',a,b)),root=g.scene||g.scenes[0];A.root=root;s.add(root);let ms=[];root.traverse(x=>x.isMesh&&ms.push(x));for(let m of ms)A.parts.push(await prep(m));$('meshName').textContent=f.name;frame();stats();msg(`Loaded ${ms.length} mesh part${ms.length===1?'':'s'}.`)}
function exp(){new E().parse(A.root,b=>{let u=URL.createObjectURL(new Blob([b])),a=document.createElement('a');a.href=u;a.download=A.name.replace(/\.glb$/i,'')+'-texture-facegroups.glb';a.click();setTimeout(()=>URL.revokeObjectURL(u),1e3)},e=>msg('Export failed: '+e.message),{binary:1})}
$('openGlbBtn').onclick=()=>$('glbInput').click();$('glbInput').onchange=e=>load(e.target.files[0]);$('openTextureBtn').onclick=()=>$('textureInput').click();$('textureInput').onchange=async e=>{let b=await createImageBitmap(e.target.files[0]);A.up=tex(b);msg('Replacement albedo loaded.')};$('frameBtn').onclick=frame;$('generateBtn').onclick=gen;$('exportBtn').onclick=exp;$('previewMode').onchange=preview;$('showOriginalBtn').onclick=()=>{$('previewMode').value='original';preview()};$('randomiseBtn').onclick=()=>{$('previewMode').value='random';preview()};$('gridToggle').onchange=e=>grid.visible=e.target.checked;$('variance').disabled=1;$('ignoreBrightness').disabled=1;$('dropZone').onclick=()=>$('glbInput').click();$('dropZone').ondragover=e=>e.preventDefault();$('dropZone').ondrop=e=>{e.preventDefault();load(e.dataTransfer.files[0])};msg('Ready — choose a GLB with UVs and an albedo texture.');stats();lists();