import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
const $=id=>document.getElementById(id), viewport=$('viewport');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x111820);
const camera=new THREE.PerspectiveCamera(45,1,.01,10000);camera.position.set(3,2,4);
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;viewport.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;
scene.add(new THREE.HemisphereLight(0xffffff,0x334455,2.2));const sun=new THREE.DirectionalLight(0xffffff,2.6);sun.position.set(4,8,6);scene.add(sun);const grid=new THREE.GridHelper(20,40,0x536272,0x2b3540);scene.add(grid);
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
const defaultSemantics=[['Skin',0xe2a58d],['Hair',0x4b3028],['Lips',0xb74f67],['Eyes',0x738da3],['Brows / Lashes',0x302520],['Other',0x87919a]];
const app={root:null,name:'model.glb',parts:[],palette:[],regions:0,uploaded:null,semantics:defaultSemantics.map((x,i)=>({id:i,name:x[0],colour:new THREE.Color(x[1]),locked:false})),activeSemantic:0,selected:null,history:[]};
function status(t){$('status').textContent=t;$('statusPill').textContent=t}
function resize(){const b=viewport.getBoundingClientRect();if(!b.width)return;camera.aspect=b.width/b.height;camera.updateProjectionMatrix();renderer.setSize(b.width,b.height,false)}new ResizeObserver(resize).observe(viewport);resize();(function loop(){requestAnimationFrame(loop);controls.update();renderer.render(scene,camera)})();
function lab(c){let[r,g,b]=c,x=(r*.4124+g*.3576+b*.1805)/.95047,y=r*.2126+g*.7152+b*.0722,z=(r*.0193+g*.1192+b*.9505)/1.08883,f=t=>t>.008856?Math.cbrt(t):7.787*t+16/116;x=f(x);y=f(y);z=f(z);return[116*y-16,500*(x-y),200*(y-z)]}
function distance(a,b){const A=lab(a),B=lab(b);return Math.hypot(A[0]-B[0],A[1]-B[1],A[2]-B[2])}
function mean(fs,p){const m=[0,0,0];for(const f of fs){const c=p.faceColours[f];m[0]+=c[0];m[1]+=c[1];m[2]+=c[2]}return m.map(v=>v/Math.max(1,fs.length))}
function stats(){const tris=app.parts.reduce((n,p)=>n+p.faceCount,0),groups=app.parts.flatMap(p=>p.groups||[]),assigned=groups.filter(g=>g.semantic>=0).length,used=new Set(groups.filter(g=>g.semantic>=0).map(g=>g.semantic)).size;$('trianglesStat').textContent=tris.toLocaleString();$('regionsStat').textContent=groups.length.toLocaleString();$('assignedStat').textContent=assigned.toLocaleString();$('semanticStat').textContent=used.toLocaleString();for(const id of['frameBtn','generateBtn'])$(id).disabled=!app.root;$('exportBtn').disabled=!assigned;$('otherBtn').disabled=!groups.length;$('undoBtn').disabled=!app.history.length}
function disposePart(p){[...(p.regionMaterials||[]),...(p.paletteMaterials||[]),...(p.semanticMaterials||[])].forEach(m=>m?.dispose?.());p.mesh?.geometry?.dispose?.()}
function clear(){if(app.root)scene.remove(app.root);app.parts.forEach(disposePart);app.root=null;app.parts=[];app.palette=[];app.regions=0;app.selected=null;app.history=[];$('meshName').textContent='No mesh loaded';$('textureMeta').textContent='No model loaded.';renderUI();stats()}
function frame(){if(!app.root)return;const b=new THREE.Box3().setFromObject(app.root),s=b.getSize(new THREE.Vector3()),m=b.getCenter(new THREE.Vector3()),d=Math.max(s.x,s.y,s.z)||1;controls.target.copy(m);camera.position.copy(m).add(new THREE.Vector3(d*1.5,d*.9,d*1.5));camera.near=Math.max(d/1000,.001);camera.far=d*1000;camera.updateProjectionMatrix()}
function adjacency(pos){const n=pos.count/3,map=new Map(),a=Array.from({length:n},()=>new Set()),key=i=>`${Math.round(pos.getX(i)*1e5)},${Math.round(pos.getY(i)*1e5)},${Math.round(pos.getZ(i)*1e5)}`;for(let f=0;f<n;f++){const v=[key(f*3),key(f*3+1),key(f*3+2)];for(const[i,j]of[[0,1],[1,2],[2,0]]){const e=v[i]<v[j]?v[i]+'|'+v[j]:v[j]+'|'+v[i];if(!map.has(e))map.set(e,[]);map.get(e).push(f)}}for(const fs of map.values())for(let i=0;i<fs.length;i++)for(let j=i+1;j<fs.length;j++)a[fs[i]].add(fs[j]),a[fs[j]].add(fs[i]);return a}
const toLinear=x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4;
function textureData(image){const w=image?.width||image?.videoWidth,h=image?.height||image?.videoHeight;if(!w||!h)throw new Error('Texture image has no readable dimensions.');const c=document.createElement('canvas'),x=c.getContext('2d',{willReadFrequently:true});c.width=w;c.height=h;x.drawImage(image,0,0,w,h);return{w,h,d:x.getImageData(0,0,w,h).data}}
function sample(tex,u,v){u=((u%1)+1)%1;v=((v%1)+1)%1;const x=Math.round(u*(tex.w-1)),y=Math.round((1-v)*(tex.h-1)),i=(y*tex.w+x)*4;return[toLinear(tex.d[i]/255),toLinear(tex.d[i+1]/255),toLinear(tex.d[i+2]/255)]}
async function prepare(mesh){const original=mesh.material,g=mesh.geometry.index?mesh.geometry.toNonIndexed():mesh.geometry.clone();g.computeVertexNormals();mesh.geometry=g;const mats=Array.isArray(original)?original:[original],map=mats.find(m=>m?.map)?.map;let tex=null;if(map?.image){try{tex=textureData(map.image)}catch(e){console.warn('Embedded texture could not be sampled:',e)}}return{mesh,original,pos:g.attributes.position,norm:g.attributes.normal,uv:g.attributes.uv,faceCount:g.attributes.position.count/3,adj:adjacency(g.attributes.position),tex,faceColours:[],ids:null,groups:[],regionMaterials:[],paletteMaterials:[],semanticMaterials:[]}}
function faceColour(p,f){const tex=app.uploaded||p.tex;if(tex&&p.uv){let u=0,v=0;for(let k=0;k<3;k++){u+=p.uv.getX(f*3+k)/3;v+=p.uv.getY(f*3+k)/3}return sample(tex,u,v)}const m=Array.isArray(p.original)?p.original[0]:p.original,c=m?.color||new THREE.Color(1,1,1);return[c.r,c.g,c.b]}
function nearest(c,pal){let best=0,d=Infinity;pal.forEach((x,i)=>{const q=distance(c,x);if(q<d){d=q;best=i}});return best}
function makePalette(k,it){const all=app.parts.flatMap(p=>p.faceColours),step=Math.max(1,Math.floor(all.length/7000)),samples=all.filter((_,i)=>i%step===0),pal=[];for(let i=0;i<k;i++)pal.push(samples[Math.min(samples.length-1,Math.floor((i+.5)*samples.length/k))]?.slice()||[.5,.5,.5]);for(let z=0;z<it;z++){const buckets=Array.from({length:k},()=>[]);for(const c of samples)buckets[nearest(c,pal)].push(c);buckets.forEach((b,i)=>{if(b.length){const q=[0,0,0];b.forEach(c=>{q[0]+=c[0];q[1]+=c[1];q[2]+=c[2]});pal[i]=q.map(v=>v/b.length)}})}return pal}
function islands(p){const seen=new Uint8Array(p.faceCount),out=[];for(let seed=0;seed<p.faceCount;seed++){if(seen[seed])continue;const pid=p.ids[seed],q=[seed],faces=[];seen[seed]=1;while(q.length){const f=q.pop();faces.push(f);p.adj[f].forEach(n=>{if(!seen[n]&&p.ids[n]===pid){seen[n]=1;q.push(n)}})}out.push({pid,faces})}return out}
function smooth(p,passes,threshold){for(let z=0;z<passes;z++){const next=new Int32Array(p.ids);let changes=0;for(let f=0;f<p.faceCount;f++){const ns=[...p.adj[f]],votes=new Map();if(!ns.length)continue;ns.forEach(n=>votes.set(p.ids[n],(votes.get(p.ids[n])||0)+1));let best=p.ids[f],count=0;votes.forEach((v,k)=>{if(v>count){count=v;best=k}});if(best!==p.ids[f]&&count/ns.length>=threshold){next[f]=best;changes++}}p.ids=next;if(!changes)break}}
function clean(p,min,passes){for(let z=0;z<passes;z++){let changes=0;for(const r of islands(p)){if(r.faces.length>=min)continue;const votes=new Map();r.faces.forEach(f=>p.adj[f].forEach(n=>{const id=p.ids[n];if(id!==r.pid)votes.set(id,(votes.get(id)||0)+1)}));let best=r.pid,count=0;votes.forEach((v,k)=>{if(v>count){count=v;best=k}});if(best!==r.pid){r.faces.forEach(f=>p.ids[f]=best);changes++}}if(!changes)break}}
function buildGraph(p){const regions=islands(p).map((r,i)=>({...r,id:i,alive:true,neighbours:new Set()})),faceRegion=new Int32Array(p.faceCount);regions.forEach(r=>r.faces.forEach(f=>faceRegion[f]=r.id));for(let f=0;f<p.faceCount;f++)p.adj[f].forEach(n=>{const a=faceRegion[f],b=faceRegion[n];if(a!==b){regions[a].neighbours.add(b);regions[b].neighbours.add(a)}});return[regions,faceRegion]}
function boundaryContrast(a,b,p,faceRegion){let sum=0,n=0;a.faces.forEach(f=>p.adj[f].forEach(x=>{if(faceRegion[x]===b.id){sum+=distance(p.faceColours[f],p.faceColours[x]);n++}}));return n?sum/n:999}
function reduceRegions(regions,p,faceRegion){const below=+$('mergeBelow').value,passes=+$('regionMergePasses').value,maxD=+$('maxRegionColourDistance').value,protect=$('protectFeatures').checked,ct=+$('contrastThreshold').value,ps=+$('protectedSize').value;for(let z=0;z<passes;z++){let changes=0;for(const a of regions.filter(r=>r.alive).sort((x,y)=>x.faces.length-y.faces.length)){if(!a.alive||a.faces.length>=below)continue;let maxContrast=0;a.neighbours.forEach(i=>{const b=regions[i];if(b?.alive)maxContrast=Math.max(maxContrast,boundaryContrast(a,b,p,faceRegion))});if(protect&&a.faces.length<=ps&&maxContrast>=ct)continue;let target=null,best=-Infinity;for(const i of a.neighbours){const b=regions[i];if(!b?.alive)continue;const ca=mean(a.faces,p),cb=mean(b.faces,p),cd=distance(ca,cb),bc=boundaryContrast(a,b,p,faceRegion);if(cd>maxD||protect&&bc>=ct)continue;let shared=0;a.faces.forEach(f=>p.adj[f].forEach(x=>{if(faceRegion[x]===b.id)shared++}));const score=shared*5-cd-bc*.5+Math.log1p(b.faces.length);if(score>best){best=score;target=b}}if(!target)continue;a.faces.forEach(f=>{target.faces.push(f);faceRegion[f]=target.id});a.neighbours.forEach(i=>{const n=regions[i];if(n?.alive&&n!==target){n.neighbours.delete(a.id);n.neighbours.add(target.id);target.neighbours.add(n.id)}});target.neighbours.delete(a.id);target.neighbours.delete(target.id);a.alive=false;changes++}if(!changes)break}return regions.filter(r=>r.alive)}
function material(colour){return new THREE.MeshStandardMaterial({color:colour instanceof THREE.Color?colour:new THREE.Color(...colour),roughness:.72,side:THREE.DoubleSide})}
function rebuildRegions(p,groups){const P=[],N=[],U=[],g=new THREE.BufferGeometry();let start=0;p.regionMaterials.forEach(m=>m.dispose());p.paletteMaterials.forEach(m=>m.dispose());p.semanticMaterials.forEach(m=>m.dispose());p.regionMaterials=[];p.paletteMaterials=[];p.semanticMaterials=[];groups.forEach(gr=>{gr.faces.forEach(f=>{for(let k=0;k<3;k++){const q=f*3+k;P.push(p.pos.getX(q),p.pos.getY(q),p.pos.getZ(q));N.push(p.norm.getX(q),p.norm.getY(q),p.norm.getZ(q));if(p.uv)U.push(p.uv.getX(q),p.uv.getY(q))}});g.addGroup(start,gr.faces.length*3,p.regionMaterials.length);start+=gr.faces.length*3;p.regionMaterials.push(material(new THREE.Color().setHSL(Math.random(),.65,.55)));p.paletteMaterials.push(material(app.palette[gr.pid]||gr.mean||[.5,.5,.5]));p.semanticMaterials.push(material(new THREE.Color(.25,.28,.32)))});g.setAttribute('position',new THREE.Float32BufferAttribute(P,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(N,3));if(U.length)g.setAttribute('uv',new THREE.Float32BufferAttribute(U,2));p.mesh.geometry=g}
function generate(){if(!app.root)return;try{status('Sampling albedo…');app.parts.forEach(p=>p.faceColours=Array.from({length:p.faceCount},(_,f)=>faceColour(p,f)));app.palette=makePalette(+$('paletteSize').value,+$('paletteIterations').value);let count=0;for(const p of app.parts){p.ids=Int32Array.from(p.faceColours.map(c=>nearest(c,app.palette)));smooth(p,+$('neighbourPasses').value,+$('majorityThreshold').value);clean(p,+$('minGroupSize').value,3);let[regions,faceRegion]=buildGraph(p);regions=reduceRegions(regions,p,faceRegion);p.groups=regions.map((r,i)=>({id:count+i,pid:r.pid,faces:r.faces,mean:mean(r.faces,p),semantic:-1}));rebuildRegions(p,p.groups);count+=p.groups.length}app.regions=count;app.selected=null;app.history=[];preview();renderUI();stats();status(`Generated ${count} source regions. Tap a region to begin semantic grouping.`)}catch(e){console.error(e);status('Generation failed: '+(e.message||e))}}
function saveHistory(){app.history.push(app.parts.map(p=>p.groups.map(g=>g.semantic)));if(app.history.length>30)app.history.shift()}
function restoreHistory(){const snap=app.history.pop();if(!snap)return;app.parts.forEach((p,i)=>p.groups.forEach((g,j)=>g.semantic=snap[i][j]));preview();renderUI();stats()}
function selectedGroup(){return app.selected?app.parts[app.selected.part]?.groups[app.selected.group]:null}
function assignSelected(){const g=selectedGroup(),sem=app.semantics[app.activeSemantic];if(!g||sem?.locked)return;saveHistory();g.semantic=app.activeSemantic;preview();renderUI();stats()}
function gather(){const seed=selectedGroup(),sem=app.semantics[app.activeSemantic];if(!seed||sem?.locked)return;saveHistory();const tolerance=+$('semanticTolerance').value,connected=$('connectedGather').checked,part=app.parts[app.selected.part];seed.semantic=app.activeSemantic;if(connected){const queue=[app.selected.group],seen=new Set(queue);while(queue.length){const gi=queue.pop(),g=part.groups[gi];for(let j=0;j<part.groups.length;j++){if(seen.has(j)||part.groups[j].semantic>=0)continue;const other=part.groups[j];if(distance(seed.mean,other.mean)<=tolerance&&regionsTouch(g,other,part)){other.semantic=app.activeSemantic;seen.add(j);queue.push(j)}}}}else app.parts.forEach(p=>p.groups.forEach(g=>{if(g.semantic<0&&distance(seed.mean,g.mean)<=tolerance)g.semantic=app.activeSemantic}));preview();renderUI();stats();status(`Gathered regions into ${sem.name}.`)}
function regionsTouch(a,b,p){const set=new Set(b.faces);return a.faces.some(f=>[...p.adj[f]].some(n=>set.has(n)))}
function unassign(){const g=selectedGroup();if(!g)return;saveHistory();g.semantic=-1;preview();renderUI();stats()}
function assignOther(){const idx=app.semantics.findIndex(s=>s.name.toLowerCase()==='other');if(idx<0)return;saveHistory();app.parts.forEach(p=>p.groups.forEach(g=>{if(g.semantic<0)g.semantic=idx}));preview();renderUI();stats()}
function preview(){const mode=$('previewMode').value;app.parts.forEach((p,pi)=>{if(mode==='original')p.mesh.material=p.original;else if(mode==='regions')p.mesh.material=p.regionMaterials;else if(mode==='palette')p.mesh.material=p.paletteMaterials;else{p.groups.forEach((g,gi)=>{let col=g.semantic>=0?app.semantics[g.semantic].colour:new THREE.Color(.22,.24,.27);if(app.selected?.part===pi&&app.selected?.group===gi)col=new THREE.Color(1,.75,.05);p.semanticMaterials[gi].color.copy(col)});p.mesh.material=p.semanticMaterials}})}
function renderUI(){const list=$('semanticList');list.innerHTML='';app.semantics.forEach((sem,i)=>{const row=document.createElement('div');row.className='groupRow'+(i===app.activeSemantic?' active':'');row.innerHTML=`<div class="swatch" style="background:#${sem.colour.getHexString()}"></div><div><div>${sem.name}</div><small>${sem.locked?'Locked':'Tap to activate'}</small></div><small>${app.parts.flatMap(p=>p.groups).filter(g=>g.semantic===i).length}</small>`;row.onclick=()=>{app.activeSemantic=i;renderUI()};list.appendChild(row)});const g=selectedGroup();$('selectionInfo').innerHTML=g?`Region <b>${g.id+1}</b><br>${g.faces.length.toLocaleString()} faces<br>Palette P${g.pid+1}<br>${g.semantic>=0?'Assigned: '+app.semantics[g.semantic].name:'Unassigned'}`:'Tap a coloured region on the model.';for(const id of['assignBtn','gatherBtn','unassignBtn','lockBtn'])$(id).disabled=!g;const summary=$('semanticSummary');summary.innerHTML='';app.semantics.forEach((sem,i)=>{const regions=app.parts.flatMap(p=>p.groups).filter(g=>g.semantic===i),faces=regions.reduce((n,g)=>n+g.faces.length,0);if(regions.length){const d=document.createElement('div');d.className='groupRow';d.innerHTML=`<div class="swatch" style="background:#${sem.colour.getHexString()}"></div><div><div>${sem.name}</div><small>${regions.length} regions · ${faces.toLocaleString()} faces</small></div>`;summary.appendChild(d)}});stats()}
function pick(event){if(!app.root||!app.regions)return;const rect=renderer.domElement.getBoundingClientRect();pointer.x=((event.clientX-rect.left)/rect.width)*2-1;pointer.y=-((event.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(app.parts.map(p=>p.mesh),false)[0];if(!hit)return;const pi=app.parts.findIndex(p=>p.mesh===hit.object),group=hit.face?.materialIndex??0;app.selected={part:pi,group};preview();renderUI()}
async function parseGlb(buffer){return new Promise((resolve,reject)=>new GLTFLoader().parse(buffer,'',resolve,reject))}
async function load(file){if(!file)return;if(!file.name.toLowerCase().endsWith('.glb')){status('Please choose a binary .glb file.');return}status(`Reading ${file.name}…`);try{const buffer=await file.arrayBuffer();const gltf=await parseGlb(buffer);const root=gltf.scene||gltf.scenes?.[0];if(!root)throw new Error('The GLB contains no scene.');const meshes=[];root.traverse(o=>{if(o.isMesh&&o.geometry)meshes.push(o)});if(!meshes.length)throw new Error('The GLB contains no mesh geometry.');clear();app.name=file.name;app.root=root;scene.add(root);for(let i=0;i<meshes.length;i++){status(`Preparing mesh ${i+1} of ${meshes.length}…`);app.parts.push(await prepare(meshes[i]))}$('meshName').textContent=file.name;$('textureMeta').textContent=app.parts.some(p=>p.tex)?'Embedded albedo detected.':'No embedded albedo detected. Load a replacement albedo if required.';frame();renderUI();stats();status(`Loaded ${meshes.length} mesh part${meshes.length===1?'':'s'}.`)}catch(e){console.error(e);status('Load failed: '+(e.message||e))}}
async function loadAlbedo(file){if(!file)return;try{status(`Reading ${file.name}…`);const bitmap=await createImageBitmap(file);app.uploaded=textureData(bitmap);bitmap.close?.();$('textureMeta').textContent=`Replacement albedo loaded: ${file.name} (${app.uploaded.w}×${app.uploaded.h}).`;status('Replacement albedo loaded. Generate regions to apply it.')}catch(e){console.error(e);status('Albedo load failed: '+(e.message||e))}}
function exportSemantic(){const assigned=app.parts.flatMap(p=>p.groups).some(g=>g.semantic>=0);if(!assigned)return;for(const p of app.parts){const final=[];app.semantics.forEach((sem,si)=>{const faces=p.groups.filter(g=>g.semantic===si).flatMap(g=>g.faces);if(faces.length)final.push({faces,mean:sem.colour.toArray(),name:sem.name})});rebuildRegions(p,final.map((g,i)=>({pid:i,...g})));p.mesh.material=final.map(g=>{const m=material(g.mean);m.name=g.name;return m})}new GLTFExporter().parse(app.root,b=>{const url=URL.createObjectURL(new Blob([b],{type:'model/gltf-binary'})),a=document.createElement('a');a.href=url;a.download=app.name.replace(/\.glb$/i,'')+'-semantic-facegroups.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Exported semantic GLB.')},e=>status('Export failed: '+(e.message||e)),{binary:true})}
const glbInput=$('glbInput'),textureInput=$('textureInput');
$('openGlbBtn').onclick=()=>{glbInput.value='';glbInput.click()};
glbInput.onchange=async e=>{const file=e.target.files?.[0];await load(file);e.target.value=''};
$('openTextureBtn').onclick=()=>{textureInput.value='';textureInput.click()};
textureInput.onchange=async e=>{const file=e.target.files?.[0];await loadAlbedo(file);e.target.value=''};
$('frameBtn').onclick=frame;$('generateBtn').onclick=generate;$('exportBtn').onclick=exportSemantic;$('previewMode').onchange=preview;$('gridToggle').onchange=e=>grid.visible=e.target.checked;$('semanticTolerance').oninput=e=>$('toleranceOut').textContent=e.target.value;$('assignBtn').onclick=assignSelected;$('gatherBtn').onclick=gather;$('unassignBtn').onclick=unassign;$('undoBtn').onclick=restoreHistory;$('otherBtn').onclick=assignOther;$('lockBtn').onclick=()=>{const s=app.semantics[app.activeSemantic];s.locked=!s.locked;renderUI()};$('addSemanticBtn').onclick=()=>{const name=prompt('New semantic group name:');if(name){app.semantics.push({id:app.semantics.length,name,colour:new THREE.Color().setHSL(Math.random(),.6,.55),locked:false});app.activeSemantic=app.semantics.length-1;renderUI()}};$('renameSemanticBtn').onclick=()=>{const s=app.semantics[app.activeSemantic],name=prompt('Rename semantic group:',s.name);if(name){s.name=name;renderUI()}};renderer.domElement.addEventListener('pointerdown',pick);const dz=$('dropZone');dz.onclick=()=>{glbInput.value='';glbInput.click()};dz.ondragover=e=>{e.preventDefault();dz.classList.add('drag')};dz.ondragleave=()=>dz.classList.remove('drag');dz.ondrop=async e=>{e.preventDefault();dz.classList.remove('drag');const file=e.dataTransfer?.files?.[0];await load(file)};status('Ready — load a UV-mapped GLB.');renderUI();stats();