import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { GLTFExporter } from 'three/addons/exporters/GLTFExporter.js';

const $=id=>document.getElementById(id), vp=$('viewport');
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x111820);
const camera=new THREE.PerspectiveCamera(45,1,.01,10000); camera.position.set(3,2,4);
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,2)); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; vp.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement); controls.enableDamping=true;
scene.add(new THREE.HemisphereLight(0xffffff,0x334455,2.2)); const sun=new THREE.DirectionalLight(0xffffff,2.6); sun.position.set(4,8,6); scene.add(sun);
const grid=new THREE.GridHelper(20,40,0x536272,0x2b3540); scene.add(grid);
const app={root:null,name:'model.glb',parts:[],uploaded:null,uploadedInfo:null,groups:0,wires:[]};

function status(s){$('status').textContent=s;$('statusPill').textContent=s}
function resize(){const r=vp.getBoundingClientRect();if(!r.width||!r.height)return;camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false)}
new ResizeObserver(resize).observe(vp); resize();
(function loop(){requestAnimationFrame(loop);controls.update();renderer.render(scene,camera)})();
function clearWire(){app.wires.forEach(w=>scene.remove(w));app.wires=[]}
function clearModel(){clearWire();if(app.root)scene.remove(app.root);app.root=null;app.parts=[];app.groups=0;$('meshName').textContent='No mesh loaded';updateMeta();updateList();stats()}
function frame(){if(!app.root)return;const b=new THREE.Box3().setFromObject(app.root),s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3()),d=Math.max(s.x,s.y,s.z)||1;controls.target.copy(c);camera.position.copy(c).add(new THREE.Vector3(d*1.5,d*.9,d*1.5));camera.near=Math.max(d/1000,.001);camera.far=d*1000;camera.updateProjectionMatrix()}
function stats(){let tris=0;app.parts.forEach(p=>tris+=p.faceCount);$('trianglesStat').textContent=Math.round(tris).toLocaleString();$('groupsStat').textContent=app.groups.toLocaleString();$('meshesStat').textContent=app.parts.length.toLocaleString();$('sourceStat').textContent=$('sourceMode').selectedOptions[0]?.text||'—';const loaded=!!app.root;$('frameBtn').disabled=!loaded;$('generateBtn').disabled=!loaded;$('exportBtn').disabled=!loaded;$('showOriginalBtn').disabled=!loaded;$('randomiseBtn').disabled=!app.groups}
function updateMeta(){if(!app.root){$('textureMeta').textContent='No texture loaded.';return}const a=[];if(app.uploadedInfo)a.push(`Uploaded: ${app.uploadedInfo.name} (${app.uploadedInfo.width}×${app.uploadedInfo.height})`);const p=app.parts.find(x=>x.embeddedInfo);if(p)a.push(`Embedded: ${p.embeddedInfo.name} (${p.embeddedInfo.width}×${p.embeddedInfo.height})`);if(!a.length)a.push('No albedo detected; vertex or material colour can still be used.');a.push(`Current source mode: ${$('sourceMode').selectedOptions[0]?.text}`);$('textureMeta').innerHTML=a.join('<br>')}
function parseGLB(buf){return new Promise((res,rej)=>new GLTFLoader().parse(buf,'',res,rej))}
async function imageCanvas(img){if(!img)return null;await img.decode?.().catch(()=>{});const w=img.width||img.videoWidth,h=img.height||img.videoHeight;if(!w||!h)return null;const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0,w,h);return{ctx:x,width:w,height:h}}
function bitmapCanvas(b){const c=document.createElement('canvas');c.width=b.width;c.height=b.height;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(b,0,0);return{ctx:x,width:b.width,height:b.height}}
function srgb(v){return v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4)}
function sample(t,u,v){u=((u%1)+1)%1;v=((v%1)+1)%1;const x=u*(t.width-1),y=(1-v)*(t.height-1),x0=Math.floor(x),y0=Math.floor(y),x1=Math.min(t.width-1,x0+1),y1=Math.min(t.height-1,y0+1),tx=x-x0,ty=y-y0;const get=(px,py)=>{const d=t.ctx.getImageData(px,py,1,1).data;return[srgb(d[0]/255),srgb(d[1]/255),srgb(d[2]/255)]};if($('filterMode').value==='nearest')return get(Math.round(x),Math.round(y));const a=get(x0,y0),b=get(x1,y0),c=get(x0,y1),d=get(x1,y1),o=[0,0,0];for(let i=0;i<3;i++){const p=a[i]*(1-tx)+b[i]*tx,q=c[i]*(1-tx)+d[i]*tx;o[i]=p*(1-ty)+q*ty}return o}
function lab(c){let[r,g,b]=c;let x=(r*.4124+g*.3576+b*.1805)/.95047,y=r*.2126+g*.7152+b*.0722,z=(r*.0193+g*.1192+b*.9505)/1.08883;const f=t=>t>.008856?Math.cbrt(t):7.787*t+16/116;x=f(x);y=f(y);z=f(z);return[116*y-16,500*(x-y),200*(y-z)]}
function dist(a,b){const A=lab(a),B=lab(b),dl=$('ignoreBrightness').checked?0:A[0]-B[0];return Math.hypot(dl,A[1]-B[1],A[2]-B[2])/1.5}
function key(pos,i){return`${Math.round(pos.getX(i)*1e5)},${Math.round(pos.getY(i)*1e5)},${Math.round(pos.getZ(i)*1e5)}`}
function adjacency(pos){const n=pos.count/3,m=new Map(),a=Array.from({length:n},()=>new Set());for(let f=0;f<n;f++){const v=[key(pos,f*3),key(pos,f*3+1),key(pos,f*3+2)];for(const[p,q]of[[0,1],[1,2],[2,0]]){const e=v[p]<v[q]?v[p]+'|'+v[q]:v[q]+'|'+v[p];if(!m.has(e))m.set(e,[]);m.get(e).push(f)}}m.forEach(fs=>{for(let i=0;i<fs.length;i++)for(let j=i+1;j<fs.length;j++){a[fs[i]].add(fs[j]);a[fs[j]].add(fs[i])}});return a}
function bary(){const n=+$('sampleCount').value;if(n===1)return[[1/3,1/3,1/3]];if(n===4)return[[1/3,1/3,1/3],[.65,.175,.175],[.175,.65,.175],[.175,.175,.65]];return[[1/3,1/3,1/3],[.7,.15,.15],[.15,.7,.15],[.15,.15,.7],[.5,.5,0],[0,.5,.5],[.5,0,.5]]}
async function prep(mesh){const original=mesh.material,g=mesh.geometry.index?mesh.geometry.toNonIndexed():mesh.geometry.clone();g.computeVertexNormals();mesh.geometry=g;const mats=Array.isArray(original)?original:[original],tex=mats.find(m=>m?.map)?.map||null,canvas=tex?await imageCanvas(tex.image):null;return{mesh,original,position:g.attributes.position,normal:g.attributes.normal,uv:g.attributes.uv,color:g.attributes.color,faceCount:g.attributes.position.count/3,adj:adjacency(g.attributes.position),embedded:canvas,embeddedInfo:canvas?{name:tex.name||'Embedded albedo',width:canvas.width,height:canvas.height}:null,faceColours:[],generated:[],avgMats:[],randomMats:[]}}
function source(p){const mode=$('sourceMode').value;if(mode==='uploaded')return app.uploaded?{kind:'uploaded',tex:app.uploaded}:null;if(mode==='embedded')return p.embedded?{kind:'embedded',tex:p.embedded}:null;if(mode==='vertex')return p.color?{kind:'vertex'}:null;if(mode==='material')return{kind:'material'};if(app.uploaded)return{kind:'uploaded',tex:app.uploaded};if(p.embedded)return{kind:'embedded',tex:p.embedded};if(p.color)return{kind:'vertex'};return{kind:'material'}}
function materialColour(p){const m=Array.isArray(p.original)?p.original[0]:p.original,c=m?.color||new THREE.Color(1,1,1);return[c.r,c.g,c.b]}
function faceColour(p,f,s){const out=[],pat=bary(),base=materialColour(p);for(const w of pat){let c=base.slice();if((s.kind==='uploaded'||s.kind==='embedded')&&p.uv){let u=0,v=0;for(let k=0;k<3;k++){u+=p.uv.getX(f*3+k)*w[k];v+=p.uv.getY(f*3+k)*w[k]}c=sample(s.tex,u,v)}else if(s.kind==='vertex'&&p.color){c=[0,0,0];for(let k=0;k<3;k++){c[0]+=p.color.getX(f*3+k)*w[k];c[1]+=p.color.getY(f*3+k)*w[k];c[2]+=p.color.getZ(f*3+k)*w[k]}}out.push(c)}return out.reduce((a,c)=>a.map((x,i)=>x+c[i]),[0,0,0]).map(x=>x/out.length)}
function mat(c){return new THREE.MeshStandardMaterial({color:new THREE.Color(c[0],c[1],c[2]),roughness:.72,metalness:0,side:THREE.DoubleSide})}
function rebuild(p,groups){const P=[],N=[],U=[],C=[],g=new THREE.BufferGeometry();let start=0;p.avgMats.forEach(m=>m.dispose());p.randomMats.forEach(m=>m.dispose());p.avgMats=[];p.randomMats=[];groups.forEach((gr,i)=>{gr.faces.forEach(f=>{for(let k=0;k<3;k++){const q=f*3+k;P.push(p.position.getX(q),p.position.getY(q),p.position.getZ(q));N.push(p.normal.getX(q),p.normal.getY(q),p.normal.getZ(q));if(p.uv)U.push(p.uv.getX(q),p.uv.getY(q));if(p.color)C.push(p.color.getX(q),p.color.getY(q),p.color.getZ(q))}});g.addGroup(start,gr.faces.length*3,i);start+=gr.faces.length*3;p.avgMats.push(mat(gr.mean));p.randomMats.push(new THREE.MeshStandardMaterial({color:new THREE.Color().setHSL(Math.random(),.65,.55),roughness:.72,side:THREE.DoubleSide}))});g.setAttribute('position',new THREE.Float32BufferAttribute(P,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(N,3));if(U.length)g.setAttribute('uv',new THREE.Float32BufferAttribute(U,2));if(C.length)g.setAttribute('color',new THREE.Float32BufferAttribute(C,3));p.mesh.geometry=g}
function generate(){if(!app.parts.length)return;try{status('Sampling albedo texture…');let total=0;for(const p of app.parts){const s=source(p);if(!s)throw new Error('Selected colour source is unavailable.');p.faceColours=Array.from({length:p.faceCount},(_,f)=>faceColour(p,f,s));const labels=new Int32Array(p.faceCount);labels.fill(-1);let groups=[];for(let seed=0;seed<p.faceCount;seed++){if(labels[seed]>=0)continue;const gi=groups.length,q=[seed],faces=[];labels[seed]=gi;let mean=p.faceColours[seed].slice();while(q.length){const f=q.pop();faces.push(f);mean=[(mean[0]*(faces.length-1)+p.faceColours[f][0])/faces.length,(mean[1]*(faces.length-1)+p.faceColours[f][1])/faces.length,(mean[2]*(faces.length-1)+p.faceColours[f][2])/faces.length];p.adj[f].forEach(nb=>{if(labels[nb]<0&&dist(p.faceColours[nb],mean)<=+$('variance').value){labels[nb]=gi;q.push(nb)}})}groups.push({faces,mean})}if($('mergeTiny').checked){const min=Math.max(1,+$('minGroupSize').value||1);for(let i=0;i<groups.length;i++){const gr=groups[i];if(!gr.faces.length||gr.faces.length>=min)continue;const votes=new Map();gr.faces.forEach(f=>p.adj[f].forEach(nb=>{const o=labels[nb];if(o!==i&&groups[o]?.faces.length)votes.set(o,(votes.get(o)||0)+1)}));let target=-1,best=0;votes.forEach((v,k)=>{if(v>best){best=v;target=k}});if(target>=0){gr.faces.forEach(f=>{labels[f]=target;groups[target].faces.push(f)});gr.faces=[]}}groups=groups.filter(g=>g.faces.length)}groups.forEach(g=>g.mean=g.faces.reduce((a,f)=>a.map((x,i)=>x+p.faceColours[f][i]),[0,0,0]).map(x=>x/g.faces.length));p.generated=groups.map((g,i)=>({id:total+i+1,...g}));rebuild(p,p.generated);total+=p.generated.length}app.groups=total;updateList();$('previewMode').value='groupAverage';preview();stats();status(`Generated ${total} facegroups from texture colours.`)}catch(e){console.error(e);status('Generation failed: '+(e.message||e))}}
function preview(){const mode=$('previewMode').value;app.parts.forEach(p=>{if(mode==='original')p.mesh.material=p.original;else if(mode==='random'&&p.randomMats.length)p.mesh.material=p.randomMats;else if(p.avgMats.length)p.mesh.material=p.avgMats;else p.mesh.material=p.original});clearWire();if($('wireToggle').checked)app.parts.forEach(p=>{const w=new THREE.LineSegments(new THREE.WireframeGeometry(p.mesh.geometry),new THREE.LineBasicMaterial({color:0xffffff,transparent:true,opacity:.28}));w.applyMatrix4(p.mesh.matrixWorld);scene.add(w);app.wires.push(w)})}
function updateList(){const list=$('groupList');list.innerHTML='';const groups=app.parts.flatMap(p=>p.generated||[]);if(!groups.length){list.innerHTML='<div class="empty">Generate facegroups to inspect colour regions.</div>';return}groups.forEach(g=>{const c=new THREE.Color(g.mean[0],g.mean[1],g.mean[2]),r=document.createElement('div');r.className='groupRow';r.innerHTML=`<div class="swatch" style="background:#${c.getHexString()}"></div><div><div>Group ${g.id}</div><small>${g.faces.length.toLocaleString()} faces</small></div><small>#${g.id}</small>`;list.appendChild(r)})}
async function loadGLB(file){if(!file)return;if(!file.name.toLowerCase().endsWith('.glb')){status('Please choose a .glb file.');return}clearModel();app.name=file.name;status(`Reading ${file.name}…`);try{const gltf=await parseGLB(await file.arrayBuffer()),root=gltf.scene||gltf.scenes?.[0];if(!root)throw new Error('No scene in GLB.');app.root=root;scene.add(root);const meshes=[];root.traverse(o=>{if(o.isMesh&&o.geometry)meshes.push(o)});if(!meshes.length)throw new Error('No mesh geometry.');for(let i=0;i<meshes.length;i++){status(`Preparing mesh ${i+1} of ${meshes.length}…`);app.parts.push(await prep(meshes[i]))}$('meshName').textContent=file.name;frame();updateMeta();stats();status(`Loaded ${meshes.length} mesh part${meshes.length===1?'':'s'}.`)}catch(e){console.error(e);clearModel();status('Load failed: '+(e.message||e))}finally{$('glbInput').value=''}}
async function loadTexture(file){if(!file)return;try{const b=await createImageBitmap(file);app.uploaded=bitmapCanvas(b);app.uploadedInfo={name:file.name,width:b.width,height:b.height};updateMeta();status(`Loaded replacement albedo: ${file.name}.`)}catch(e){status('Texture load failed: '+(e.message||e))}finally{$('textureInput').value=''}}
function exportGLB(){if(!app.root)return;status('Exporting…');new GLTFExporter().parse(app.root,r=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([r],{type:'model/gltf-binary'}));a.href=u;a.download=app.name.replace(/\.glb$/i,'')+'-texture-facegroups.glb';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);status('Exported GLB.')},e=>status('Export failed: '+e.message),{binary:true,onlyVisible:true})}
function demo(){clearModel();const g=new THREE.SphereGeometry(1,48,24).toNonIndexed(),p=g.attributes.position,uv=[];for(let i=0;i<p.count;i++){const v=new THREE.Vector3(p.getX(i),p.getY(i),p.getZ(i)).normalize();uv.push(.5+Math.atan2(v.z,v.x)/(2*Math.PI),.5-Math.asin(v.y)/Math.PI)}g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.fillStyle='#c93f3f';x.fillRect(0,0,256,256);x.fillStyle='#397dd5';x.fillRect(30,20,90,210);x.fillStyle='#57a857';x.beginPath();x.arc(185,128,48,0,Math.PI*2);x.fill();const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({map:t,roughness:.75}));app.root=new THREE.Group();app.root.add(m);scene.add(app.root);app.name='demo.glb';prep(m).then(q=>{app.parts=[q];$('meshName').textContent='Demo sphere';frame();updateMeta();stats();status('Demo loaded — click Generate Facegroups.')})}

$('openGlbBtn').onclick=()=>$('glbInput').click();$('openTextureBtn').onclick=()=>$('textureInput').click();$('glbInput').onchange=e=>loadGLB(e.target.files?.[0]);$('textureInput').onchange=e=>loadTexture(e.target.files?.[0]);$('demoBtn').onclick=demo;$('frameBtn').onclick=frame;$('generateBtn').onclick=generate;$('exportBtn').onclick=exportGLB;$('showOriginalBtn').onclick=()=>{$('previewMode').value='original';preview()};$('randomiseBtn').onclick=()=>{app.parts.forEach(p=>p.randomMats.forEach(m=>m.color.setHSL(Math.random(),.65,.55)));$('previewMode').value='random';preview()};$('previewMode').onchange=preview;$('wireToggle').onchange=preview;$('gridToggle').onchange=e=>grid.visible=e.target.checked;$('sourceMode').onchange=()=>{updateMeta();stats()};$('variance').oninput=e=>$('varianceOut').textContent=e.target.value+'%';const dz=$('dropZone');dz.onclick=()=>$('glbInput').click();['dragenter','dragover'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>loadGLB(e.dataTransfer?.files?.[0]));
status('Ready — choose a GLB with UVs and an albedo texture.');updateMeta();stats();
